### ISSUE TITLE
Updates for database

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/qaava#6]
Kaavamaarays-table to many-to-many relation, since if there are multiple geometries with the same order, currently is over written.

"Title"-field (otsikko) for Dokumentti-table

Geometrytype names accordingly: alue=1, piste=3: piste <-> alue 

Kaavaelementtityyppi into three views based on geometry

**Comment by mvaaltola** [comment]
@SannaJokela instead of splitting kaavaelementtityyppi into 3 views in the DB, an alternate approach could be to separate kaavaelementtityyppi by geometry type in the QGIS project. This would be a more simple solution and avoids some potential issues with the views.

Here's how it would work in practice:

1. create 3 copies of `kaavaelementtityyppi` layer (duplicate it)
2. rename the layers to `kaavaelementtityyppi - piste`, `kaavaelementtityyppi - viiva`, `kaavaelementtityyppi - alue`
3. for each of the layers set a filter expression, e.g. for `kaavaelementtityyppi - alue` set `"gid_geometria_tyyppi" = 1`
4. update the relations in the project properties, e.g.:
![image](https://user-images.githubusercontent.com/33040018/92235351-347b9c80-eebc-11ea-83fe-97cf459a909e.png)


This way only the `kaavaelementtityyppi` options corresponding to each `kaavaelementti` geometry type are displayed in the form. E.g. only `kaavaelementtityyppi` features where geom type is point (3) are shown for `kaavaelementti - piste`.

**Comment by SannaJokela** [comment]
Corrections have been done to QGIS profile based on the database modifications.

**Comment by SannaJokela** [comment]
Additional wish:

- Modifier info from user interface, to all tables?
